### ISSUE TITLE
flatMap 的示例有误

### ISSUE THREAD

**Issue by zhuweiyou** [InterviewMap/CS-Interview-Knowledge-Map#153]
https://github.com/InterviewMap/CS-Interview-Knowledge-Map/blob/master/JS/JS-en.md#mapflatmap-and-reduce

```js
[1, [2], 3].flatMap((v) => v + 1)
// -> [2, 3, 4]
```
上面这个，运行结果是不正确的，而且没有表达 flatMap 的作用
应该是类似这样
```js
const arr = [1, 2, 3, 4]
arr.map(x => [x * 2])
// [[2], [4], [6], [8]]

arr.flatMap(x => [x * 2])
// [2, 4, 6, 8]
```

**Comment by TENCHIANG** [comment]
对，其实要使用 `[1, [2], 3].flatMap(v => v).map(v => v + 1)` 就对了
flatMap 的回调函数，参数分别是 element, index, array，所以在 flatMap 时，还是会碰到数组的
flatMap 之后，数组才会降一层维度

**Comment by imondo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
